version: '3.8'
services:
  mysql:
    image: mysql:5.7
    container_name: mysql_container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 4gYTbVt5
      MYSQL_DATABASE: aluraManager
      MYSQL_USER: aluraManagerAdmin
      MYSQL_PASSWORD: 872663
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - db_network

volumes:
  db_data:

networks:
  db_network:
