CREATE TABLE Course (
    id BIGINT(20) NOT NULL AUTO_INCREMENT,
    name VARCHAR(255) NOT NULL,
    code VARCHAR(10) NOT NULL CHECK (CHAR_LENGTH(code) BETWEEN 4 AND 10),
    instructorId BIGINT(20) NOT NULL,
    description VARCHAR(255),
    status enum('ACTIVE', 'INACTIVE') NOT NULL DEFAULT 'ACTIVE',
    inactivationDate DATETIME DEFAULT NULL,
    createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    CONSTRAINT fk_instructor FOREIGN KEY (instructorId) REFERENCES User(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci ROW_FORMAT=DYNAMIC;
