spring:
  application:
    name: ProjetoAlura

  datasource:
    url: jdbc:mysql://localhost:3306/aluraManager?useSSL=false&serverTimezone=UTC&createDatabaseIfNotExist=true
    username: aluraManagerAdmin
    password: 872663

  jpa:
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

  flyway:
    validate-on-migrate: false
