spring:
  application:
    name: ProjetoAlura
  jwt:
    key: 4Z^XrroxR@dWxqf$mTTKwW$!@#qGr4P
    issuer: alura-challenge-api

  datasource:
    url: jdbc:mysql://localhost:3306/aluraManager?useSSL=false&serverTimezone=UTC&createDatabaseIfNotExist=true
    username: aluraManagerAdmin
    password: 872663
  flyway:
    enabled: true
    locations: classpath:db/migration

  jpa:
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect



